version: "3.7"

services:

  workout-portal-api-service:
    build: .
    image: api
    restart: unless-stopped
    ports:
      - "8080:8080"
    container_name: workout-portal-api-service
    environment:
      WAIT_HOSTS: workout-portal-api-db:5432
    depends_on:
      - workout-portal-api-db
    volumes:
      - ./django_learning:/usr/src/app/django_learning
      - ./workout_portal:/usr/src/app/workout_portal

  workout-portal-ui:
    build: frontend
    image: ui
    container_name: workout-portal-ui
    restart: unless-stopped
    ports:
      - "4200:4200"   # app port
      - "49153:49153" # live-reload-port
    command: ["start"]
    depends_on:
      - workout-portal-api-service
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src

  workout-portal-api-db:
    image: postgres:10
    restart: unless-stopped
    container_name: workout-portal-api-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=django_learning
      - POSTGRES_PASSWORD=django_learning
      - POSTGRES_DB=django_learning
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data
